= Shell Redirections
:page-subtitle:
:page-tags:
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Intro

[NOTE]
====
What is described on this page targets Bash, but most things also work the same way in other shells.
====

When bash starts, it normally opens three file descriptors.
We associated them with the numbers 0, 1 and 2.

* `0` is the standard input, or STDIN;
* `1` is the starndard output, or STDOUT;
* `2` is the standard error, or STDERR;

The numbers are used a lot in command line and shell scripts, as we shall see with several examples along this page.

In C, it is simple to send output to both STDOUT and STDERR.

[source,c]
----
#include <stdio.h>

int main(void) {
  fprintf(stdout, "%s\n", "OK");
  fprintf(stderr, "%s\n", "ERR");
  return 0;
}
----

In the shell, we use the `<`, `>` and `&` operators in combination with the numbers.

== stdout

When we print or echo something, it goes to stdout by default:

[source,shell-session]
----
$ echo hey
hey

$ printf '%d\n' {1..3}
1
2
3
----

Same goes for `cat`.
By default, output goes to stdout:

[source,shell-session]
----
$ cat << EOF
> I'm $(whoami). My shell is $SHELL, version $BASH_VERSION.
> My main editor is $EDITOR, but I love Emacs too!
> EOF
I'm devy. My shell is /bin/bash, version 5.3.15(1)-release.
My main editor is vim, but I love emacs too!
----

So, it means:

[source,shell-session]
----
$ cat << EOF
Hello!
EOF
----

Is actually the same as:

[source,shell-session]
----
$ cat << EOF >&1
Hello!
EOF
----

That is, `>&1` is the explicit way to say “send the output to STDOUT.”

And by the way, the only position where the redirection operators cannot appear is between `<<` and `EOF`. The other (possible) positions are valid:

[source,text]
----
>&1 cat << EOF (OK)
cat >&1 << EOF (OK)
cat << >&1 EOF (ERR)
cat << EOF >&1 (OK)
----

