image: ruby:3.2

stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

pages:
  script:
    - gem install bundler
    - bundle install
    - git --version
    - ruby --version
    - asciidoctor --version
    - git clone https://gitlab.com/fernandobasso/adocwiki.git ./adocwiki
    - echo $PWD
    - ls -l $PWD/adocwiki
    - ruby $PWD/adocwiki/src/main.rb $PWD
    - mv -v ./build ./public
  artifacts:
    paths:
      - public
