image: ruby:3.2

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
# - test
- deploy

# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml

pages:
  stage: deploy
  script:
    - gem install bundler
    - bundle install
    - git --version
    - ruby --version
    - asciidoctor --version
    - git clone --depth 1 https://gitlab.com/fernandobasso/adocwiki.git ./adocwiki
    - echo $PWD
    - ls -l $PWD/adocwiki
    - ruby $PWD/adocwiki/src/main.rb $PWD
    - bash ./copy-assets.sh
    - mv -v ./build ./public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "devel"
  environment: production
