image: ruby:3.2

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

cache:
  paths:
    - vendor/

stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

before_script:
  - gem install bundler
  - bundle install --path vendor

pages:
  stage: deploy
  script:
    - git --version
    - ruby --version
    - asciidoctor --version
    - git clone --depth 1 https://gitlab.com/fernandobasso/adocwiki.git ./adocwiki
    - echo $PWD
    - ls -l $PWD/adocwiki
    - ruby $PWD/adocwiki/src/main.rb $PWD
    - mv -v ./build ./public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
