= Keyboard
:description: Notes on keyboard-related topics like keyboard shortcuts (keymaps, keybindings) in tools, editors, shells, etc.
:page-tags:
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Ctrl+key

It is common to have keymaps like kbd:[Ctrl+s] or kbd:[Ctrl+q].
However, keymaps like kbd:[Ctrl+;] or kbd:[Ctrl+.] mostly don't work in terminals, which meany they will not work inside tmux, vim, or emacs (in -nw) mode.

For example, in VTE-based terminals (like Terminator, or Xfce4-terminal), run `cat` then kbd:[Ctrl+;], and it simply echoes “;” back.
Try with kbd:[Ctrl+/] and it prints something like `^_`, meaning it did capture the combined keypresses correctly.

Therefore, if we try o map kbd:[Ctrl+;] in vim, for example it will not work as it will be simply interpreted as “;”.

Now try `cat` and kbd:[Alt+;], and you'll see it echoes `^[;`, meaning it correctly captured the combined keypress.

In short, `Ctrl` doesn't work with some special chars, while `Alt` does work mostly with any char available on the keyboard.
