= Keyboard
:description: Notes on keyboard-related topics like keyboard shortcuts (keymaps, keybindings) in tools, editors, shells, etc.
:page-tags:
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Ctrl+key

A keymap.

It is common to have keymaps like kbd:[Ctrl+s] or kbd:[Ctrl+q] in applications of all sorts.
However, keymaps like kbd:[Ctrl+;] or kbd:[Ctrl+.] mostly don't work in terminals, which means they will not work inside tmux, vim, or emacs (in -nw) mode.

For example, in VTE-based terminals (like Terminator, or Xfce4-terminal), run `cat` then kbd:[Ctrl+;], and it simply echoes “;” back.
Try with kbd:[Ctrl+/] and it prints something like `^_`, meaning it did capture the combined keypresses correctly.

Therefore, if we try o map kbd:[Ctrl+;] in vim, for example it will not work as it will be simply interpreted as “;”.

Now try `cat` and kbd:[Alt+;], and you'll see it echoes `^[;`, meaning it correctly captured the combined keypress.

In short, `Ctrl` doesn't work with some special chars, while `Alt` does work mostly with any char available on the keyboard.

In Kitty, `cat` then kbd:[Ctrl+;] just prints `;` (like in VTE-based terminals mentioned above), but for some reason, kbd:[Ctrl+;] still work inside vim, probably because its (advance and amazing) https://sw.kovidgoyal.net/kitty/keyboard-protocol/[keyboard protocol^].

It also happens that in some applications inside a terminal, pressing kbd:[Ctrl+Enter] produces a new line without submitting the text to the application, while in some other cases, we need kbd:[Alt+Enter] to produce new lines without submitting the text o he application.
